CREATE TABLE IF NOT EXISTS users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login text NOT NULL UNIQUE,
  email text UNIQUE,
  name text,
  password_hash text NOT NULL,
  password_salt text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  active boolean DEFAULT true NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  access_token_hash text NOT NULL UNIQUE,
  refresh_token_hash text NOT NULL UNIQUE,
  access_expires_at timestamptz NOT NULL,
  refresh_expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  closed_at timestamptz,
  device text,
  user_ip text
);

CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON sessions(user_id);
CREATE INDEX IF NOT EXISTS sessions_access_token_hash_idx ON sessions(access_token_hash);
CREATE INDEX IF NOT EXISTS sessions_refresh_token_hash_idx ON sessions(refresh_token_hash);

CREATE TABLE IF NOT EXISTS cards (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  release_name text,
  album_name text,
  event_name text,
  people text[] DEFAULT ARRAY[]::text[] NOT NULL,
  image_storage_key text NOT NULL,
  image_mime_type text NOT NULL,
  created_by int NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE cards ADD COLUMN IF NOT EXISTS image_storage_key text;
UPDATE cards SET image_storage_key = concat('legacy/cards/', id) WHERE image_storage_key IS NULL;
ALTER TABLE cards ALTER COLUMN image_storage_key SET NOT NULL;
ALTER TABLE cards DROP COLUMN IF EXISTS image_data;

CREATE INDEX IF NOT EXISTS cards_created_at_idx ON cards(created_at DESC);
CREATE INDEX IF NOT EXISTS cards_created_by_idx ON cards(created_by);

CREATE TABLE IF NOT EXISTS card_reactions (
  user_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  card_id int NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  reaction_type text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY (user_id, card_id, reaction_type),
  CONSTRAINT card_reactions_type_check CHECK (reaction_type IN ('like', 'waiting', 'owned', 'favorite'))
);

CREATE INDEX IF NOT EXISTS card_reactions_card_id_idx ON card_reactions(card_id);
