DROP TABLE IF EXISTS card_reactions CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login text NOT NULL UNIQUE,
  email text UNIQUE,
  name text,
  password_hash text NOT NULL,
  password_salt text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  active boolean DEFAULT true NOT NULL
);

CREATE TABLE sessions (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  access_token_hash text NOT NULL UNIQUE,
  refresh_token_hash text NOT NULL UNIQUE,
  access_expires_at timestamptz NOT NULL,
  refresh_expires_at timestamptz NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  closed_at timestamptz,
  device text,
  user_ip text
);

CREATE INDEX sessions_user_id_idx ON sessions(user_id);
CREATE INDEX sessions_access_token_hash_idx ON sessions(access_token_hash);
CREATE INDEX sessions_refresh_token_hash_idx ON sessions(refresh_token_hash);

CREATE TABLE cards (
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  release_name text,
  album_name text,
  event_name text,
  people text[] DEFAULT ARRAY[]::text[] NOT NULL,
  image_storage_key text NOT NULL,
  image_mime_type text NOT NULL,
  created_by int NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX cards_created_at_idx ON cards(created_at DESC);
CREATE INDEX cards_created_by_idx ON cards(created_by);

CREATE TABLE card_reactions (
  user_id int NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  card_id int NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  reaction_type text NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  PRIMARY KEY (user_id, card_id, reaction_type),
  CONSTRAINT card_reactions_type_check CHECK (reaction_type IN ('like', 'waiting', 'owned', 'favorite'))
);

CREATE INDEX card_reactions_card_id_idx ON card_reactions(card_id);
